### ISSUE TITLE
남은 실험 리스트

### ISSUE THREAD

**Issue by indra622** [indra622/pklGzMakerForTheano#10]
- 6/2/2로 해보기
- epoch 300으로 늘리기
- 커널 늘려서 해보기

**Comment by jeunsom** [comment]
test set confusion matrix 도출해내는 것두 해야할듓

**Comment by indra622** [comment]
다했다 confusion matrix는 천천히 하련다

**Comment by jeunsom** [comment]
Goood!! ㅋㅋ 최종 커널값 보는 것도 천천히 해봐야할듯

**Comment by indra622** [comment]
다 함
