### ISSUE TITLE
database open

### ISSUE THREAD

**Issue by jeunsom** [indra622/pklGzMakerForTheano#3]
DBN.py, imdb.py에서 database size, output parameter 수정했는데

logistic_sgd.py line 214 in load_data
train_set, valid_set, test_set = pickle.load<f> 에서 에러가 발생

**Comment by indra622** [comment]
CNN은 convolution_mlp.py돌리면 되구
저거는 왜 에러가 발생한다냐
윈도우에서해서그런가?

**Comment by indra622** [comment]
윈도우에서 만들어야될거같은데 문제는 메모리가....

**Comment by indra622** [comment]
Logistic sgd 파일을 확인해보믄 될듯?

**Comment by jeunsom** [comment]
File.pkl.gz ->>> filen.pkl.gz 수정
파일명에 File 과 같은 지정된 명칭이 들어가면 안 되는 문제였는 둣
