### ISSUE TITLE
Validation err 0%

### ISSUE THREAD

**Issue by jeunsom** [indra622/pklGzMakerForTheano#4]
Batchsize 50이하에 db 100*46, kernel size 유지하고 conv layer 2개 final output 5개써서 계산했는데 validation err이 0퍼로 나오면서 최종 테스트까지 전체를 수행했으나 실패한듯. 어딘지 파라미터의 문제인가 layer나 patch크기의 문제인가

**Comment by jeunsom** [comment]
https://groups.google.com/forum/#!topic/theano-users/teP1Ujx6m2E
여기를 읽어보니 db생성시에 섞지 않아서 발생하는 문제인 것 같다고 한 사람도 있음.

**Comment by jeunsom** [comment]
train_set_x = np.ndarray((660,4096), dtype = 'int64')
train_set_y = np.ndarray((660,1), dtype = 'int64')

i = 0
for ind in range(0,660):
    train_set_y[ind] = i
    i+=1
    if i == 3:
        i = 0

for loop in range(1,7):
    for ind in range(659,0,-1):
        j = randint(0,ind)
        temp = train_set_y[j]
        train_set_y[j] = train_set_y[ind]
        train_set_y[ind] = temp

요러면 섞어지나?

**Comment by indra622** [comment]
일단 이건 해결됐으니 닫을게염
