### ISSUE TITLE
CNN 제대로 공부해서 성능 올려보기

### ISSUE THREAD

**Issue by indra622** [indra622/pklGzMakerForTheano#8]
![image](https://cloud.githubusercontent.com/assets/7467605/16088516/747b2360-3362-11e6-8bde-e87233920ebd.png)

**Comment by indra622** [comment]
출처가 어딘지를 모르겠다

**Comment by jeunsom** [comment]
출처 찾았음
https://www.youtube.com/watch?v=vXj4z_Vo8G0

**Comment by indra622** [comment]
성능을 올리는 것은 끝이 없지
